first init

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,17 +3,17 @@ name: CI/CD
 on: push
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
+    build:
+        runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@v2
+        steps:
+            - uses: actions/checkout@v2
 
-      - name: Run a one-line script
-        run: echo "Hello, CI/CD!"
+            - name: Run a one-line script
+              run: echo "Hello, CI/CD!"
 
-      #- name: Simulate an error
-      #  run: echo "About to fail" ; exit 1
+            - name: Simulate an error
+              run: echo "About to fail" ; exit 1
 
-      - name: Another greeting
-        run: echo "Hello, CI/CD again!"
+            - name: Another greeting
+              run: echo "Hello, CI/CD again!"
